### ISSUE TITLE
[Question] Name of folder metadata vs src

### ISSUE THREAD

**Issue by xoob** [ForceDotComLabs/sldsx#4]
I noticed you are using `/metadata` as the base folder for your Salesforce source code. We are looking into ways to make the base folder configurable on Cloud9, so I wanted to ask a few questions:

- Are there other common names used for the base folder?
  - I've seen `/src` being used a lot.
- Do you ever see base folders nested in other folders?
  - For example, something like `/src/salesforce/metadata`
- Is `/metadata` the default directory for a particular tool you are using?
- How do you configure the base folder in your current IDE and tooling?

Thanks in advance for helping us understand this better!

/cc @nightwing

**Comment by dcarroll** [comment]
Metadata is the name of the folder that is created when you unzip a package
created in Force.com <http://force.com>. So, that's the only "reason".

Dave Carroll

On Sep 22, 2015, at 9:19 AM, Alex Brausewetter <notifications@github.com>
wrote:

I noticed you are using /metadata as the base folder for your Salesforce
source code. We are looking into ways to make the base folder configurable
on Cloud9, so I wanted to ask a few questions:

   - Are there other common names used for the base folder?
      - I've seen /src being used a lot.
   - Do you ever see base folders nested in other folders?
      - For example, something like /src/salesforce/metadata
   - Is /metadata the default directory for a particular tool you are using?
   - How do you configure the base folder in your current IDE and tooling?

Thanks in advance for helping us understand this better!

/cc @nightwing <https://github.com/nightwing>

—
Reply to this email directly or view it on GitHub
<https://github.com/ForceDotComLabs/sldsx/issues/4>.
